### ISSUE TITLE
Powerbank for TX2

### ISSUE THREAD

**Issue by LFiveAV** [LFiveAV/RC-car#15]

**Comment by junjiel** [comment]
**Power bank for laptop:**
Output voltage: 2-20v
Capacity: 20000-250000mAh

The link for the product(sorry it's in Chinese):
[https://detail.tmall.com/item.htm?spm=a220m.1000858.1000725.1.67021283YP4hVS&id=531803462694&skuId=3848815885899&areaId=510100&user_id=2123159866&cat_id=2&is_b=1&rn=2f737bf23babc9ea081dad5159333ec5](url)

**Comment by junjiel** [comment]
Powerbank Huawei cp12s:
https://item.jd.com/100004673786.html#crumb-wrap

USB to 5.5mm*2.5mm jack:
https://item.jd.com/4614569.html#crumb-wrap
