### ISSUE TITLE
H-Bridge

### ISSUE THREAD

**Issue by LFiveAV** [LFiveAV/RC-car#17]

**Comment by krlhrnbrnt** [comment]
https://www.electrokit.com/produkt/motordrivare-l298-dubbel-h-brygga-5-35v-2a/?gclid=CjwKCAjw2cTmBRAVEiwA8YMgzRzkTProGGD7EFRmOHS0hpHgCf6nJShtNjA7E8FpOGfNv24Ed-jYdxoC9IgQAvD_BwE
