### ISSUE TITLE
Calibrate camera on TX2

### ISSUE THREAD

**Issue by LFiveAV** [LFiveAV/RC-car#25]

**Comment by DanielTorres2** [comment]
Camera matrix = [1.24642213e+03 0.00000000e+00 8.60392755e+02
                             0.00000000e+00 1.66272377e+03 6.02788132e+02
                             0.00000000e+00 0.00000000e+00 1.00000000e+00]

Distortion coefficients = [ 1.58370225e-01 -2.54779519e-01 -6.55272730e-03  1.94108075e-05
  -1.54663447e-02]

Execute 'cv2.undistort(Image, Camera matrix, Distortion coefficients, None, Camera matrix)' to undistort Image. Code can be found in home/calibrate_camera/CalibrateCamera.py

![Undistorted_Example](https://user-images.githubusercontent.com/48914786/58555046-cfe18480-8218-11e9-89ba-f9cc1cbc9a51.png)
